# Numpy Assignment

Numpy is a library for numerical computing.

This self-guided exercise covers the important numpy commands which will be used in the programming assignments for this course. 

Basics: NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.
For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis i.e. just a single row. That axis has a length of 3. 

# Array Creation

Numpy arrays behave similar to n-dimensional matrices in matlab.

There are several ways to create an array: Two methods are shown below. Before moving ahead, lets first import numpy.  

In [1]:
# Just run this code cell by pressing shift+enter
import numpy as np

In [2]:
# Method 1 for creating an array: passing a list of numbers.
a=np.array([3,6,2])
print(a)

[3 6 2]


In [3]:
# Create an array b having elements 9,6,3,1. 
# In the code below, remove None and write the numpy command to create an array having these elements. 
b = None
print(b)

None


 If you simply pass numbers as attributes, this will give an error. example: np.array(9,6,3,1) will give an error. Try it yourself in the code cell below.

In [8]:
b = np.array([9,6,3,1])

Array transforms sequences of sequences into two-dimensional arrays. Sequences of sequences of sequences into three-dimensional arrays, and so on. Run example below which is a 2-dimensional array.

In [9]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


Example of 3-dimensional array:

In [10]:
# Just run this code cell: 
c = np.array([[[1,2,3],[4,5,6]],[[6,7,8],[9,10,11]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [11]:
# Create a 2-dimensional array having elemnets [15,16,17] in the first row and [18,19,20 ] in the second row.
c = None
print(c)

None


Method 2 for creating an array: using the "arange" function.  Numpy has a function called arange which is analogous to range function of python. arange function returns array instead of list. Example shown below.

In [12]:
# Run this code cell
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [13]:
# Run this code cell
b = np.arange(1,10,2)
# Creates an array of 1-dimension. The array values starts at 1, increments by 2 upto 10 (but not including 10). 
print(b)

[1 3 5 7 9]


In [14]:
# Create 1-d array using arange having elements from 1 to 15
c = None
print(c)

None


# Important attributes of the array object.
Attribute description is given in the comments of the respective code cells.


In [15]:
# Run this cell
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [16]:
# ndarray.ndim gives the number of axes(dimensions) of the array. Run this cell
a.ndim

2

In [17]:
# ndarray.shape gives the tuple having the shape of the array. Run this cell. 
# Here, you can interpret the shape of a as having 2 rows and 3 columns.
a.shape

(2, 3)

In [18]:
# ndarray.size the total number of elements of the array. This is equal to the product of the elements of shape.
a.size

6

In [19]:
# ndarray.dtype an object describing the type of the elements in the array.
a.dtype

dtype('int32')

In [20]:
# Create a numpy array having elements [1,2,3,4,5] in first row and [6,7,8,9,10] in the second row. 
b = None
print(b)
# Find the attributes shown in the above 4 cells.  Write the code below.


None


In [21]:
# Sometimes we want to get an individual dimension of an array.  
# We can index which dimension we want from the shape attribute.
print("To get the first dimension:")
print(a.shape[0])
print("To get the second dimension:")
print(a.shape[1])

To get the first dimension:
2
To get the second dimension:
3


# Creating array of zeros and ones.

In [22]:
# Array of zeros. The code below creates an array of zeros of the specified dimension.
# Code below creates an array of zeros of dimension (3,4)
a=np.zeros((3,4))
print(a)
print(a.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [23]:
# Array of ones. Here, dtype attribute specifies the data type of the elements of array. This is optional. 
# By default, it is float64 as you can see in the example of zeros above.
# Array of ones with dimensions (2,3,4)
b = np.ones( (2,3,4), dtype=np.int16 )
print(b)
print(b.dtype)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
int16


In [24]:
# Create an array of zeros of dimension (5,6) 
a=None
print(a)

None


In [25]:
# Create an array of ones of dimension (2,3)
b=None
print(b)

None


# Reshape Function.

Reshape function is used to reshape an array. See the example below. 

In [26]:
a = np.arange(15)
print("The original array a")
print(a)
print("The array a reshaped with dimensions 3x5")
print(a.reshape(3,5))

The original array a
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
The array a reshaped with dimensions 3x5
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [27]:
# Reshape function doesn't change the shape of original array. 
print("Notice that a didn't change")
print(a)
print("The dimensions of a:")
print(a.shape)

Notice that a didn't change
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
The dimensions of a:
(15,)


In [28]:
# To change the shape of original array, use this. 
a = a.reshape(3,5)
print("Notice a has been changed")
print(a)
print("The new dimensions of a:")
print(a.shape)

Notice a has been changed
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
The new dimensions of a:
(3, 5)


In [29]:
# Create an array of zeros of dimension (4,5)
b= None
print(b)
# Reshape b to dimensions (10,2).
b = None
print(b)

None
None


# Note:
Whenever you use a 1 dimensional array, it is a rank 1 array. In the later assignments, you will see that we don't prefer to use rank 1 array. So, we can convert them to rank 2 using reshape function. 

In [30]:
# Run this cell
# Here we have a rank 1 matrix. See it's shape.
a = np.array([1,2,3])
print(a)
print(a.shape)

[1 2 3]
(3,)


In [31]:
# Run this cell
a = a.reshape((3,1))
# Notice that a changed from a sequence of numbers to a sequence of sequence of numbers
print("The new shape of a")
print(a)
print("The array a's new dimensions:")
print(a.shape)

The new shape of a
[[1]
 [2]
 [3]]
The array a's new dimensions:
(3, 1)


# Numpy.random.rand and Numpy.random.randn

In [32]:
# Numpy.random.rand creates a numpy array of given dimensions where all the elements 
# are random samples from a uniform distribution over [0, 1).
# Run this code cell.
a = np.random.rand(2,3)
print(a)

[[0.97915628 0.15240798 0.06532774]
 [0.73257065 0.648544   0.94834818]]


 Numpy.random.randn creates a numpy array of given dimensions where all the elements are  samples from univariate “normal” (Gaussian) distribution of mean 0 and variance 1

In [33]:
# Run this cell
a = np.random.randn(2,10)
print(a)

[[ 1.40705531 -0.46648949  0.12204043  1.36519419 -1.83352447 -0.38566999
  -0.80800516 -0.82640128 -0.54300177  0.47129701]
 [ 1.32454826 -1.10998128  0.75919172 -0.40340188 -1.17079467  1.69505314
  -1.65439011 -0.30318466  0.74633744 -0.51375601]]


Numpy can create an array having values from the normal distribution with mean = $\mu$, and variance = $\sigma^2$.

To create a random array of elements from $N(\mu, \sigma^2)$, use: sigma = $\sigma$, and mu = $\mu$ and the numpy command:

sigma * np.random.randn(...) + mu

In [34]:
# Two-by-four array of samples from N(3, 6.25):
a=2.5 * np.random.randn(2, 4) + 3
a

array([[6.25269585, 3.48073247, 0.73076188, 5.62683438],
       [0.19760821, 3.21001342, 5.73002372, 5.01471058]])

In [35]:
# Create a numpy array dimension $3\times 5$ containing random samples with mean (mu)= 5 
# and standard deviation(sigma) = 2
b = None
print(b)

None


# Basic Operations: 
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [36]:
# Run this code cell
a = np.array( [20,30,40,50] )
b = np.arange( 1,5 )
print("The array a:")
print(a)
print("The array b:")
print(b)

The array a:
[20 30 40 50]
The array b:
[1 2 3 4]


In [37]:
# To subtract corresponding elements of array b from array a , simply write a - b as shown below
c = a - b
print(c)

[19 28 37 46]


In [38]:
# similarly we can do addition, multiplication, division of corresponding elements. Complete the code to add, multiply and divide corresponding elements of a and b.
addition = None # Add
product = None  # Multiply
ratio = None    # Divide
print("a + b:")
print(addition)
print("a * b: ")
print(product)
print("a/b:")
print(ratio)

a + b:
None
a * b: 
None
a/b:
None


In [39]:
# Square all the elements of the array b and save it in an array d
d = b**2
print(d)

[ 1  4  9 16]


In [40]:
# Take sine of all the elements of a matrix and save it in another matrix d
d=10*np.sin(a)
print(d)

[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


In [41]:
# Run this cell to see how this works
e= a<35
print(e)

[ True  True False False]


# Matrix and vector operations

Unlike in many matrix languages (like matlab), the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the dot function or the dot method:

In [42]:
# Run this cell
A = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0], [3,4]] )
print(A)
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [43]:
# Element wise product. Note: Dimensions should be same for A and B
C = A * B
print(C)

[[2 0]
 [0 4]]


In [44]:
# The dot method for matrix multiplication.
# Dimensions should be in accordance to linear algbra rule of Matrix-Matrix or Matrix-Vector multiplication.
D = A.dot(B) 
print(D)

[[5 4]
 [3 4]]


In [45]:
# Another way to multiply matrices is to use np.dot() function.
D = np.dot(A,B)
print(D)

[[5 4]
 [3 4]]


In [51]:
# Create a random matrix of dimension (3,4) and another random matrix of dimension (4,2) and find their dot product. 
# Also, check the dimensions of the resultant matrix.
mat1=np.random.randn(3,4)
mat2=np.random.randn(4,2)
dot_product=np.dot(mat1,mat2)
print("mat1:")
print(mat1)
print("mat2:")
print(mat2)
print("mat1 times mat2:")
print(dot_product)

mat1:
[[ 0.10026276  1.40654745  0.85896264  0.40760627]
 [-0.03581921 -1.29227298  1.81647101 -0.94820549]
 [ 0.19711218 -0.28520058 -1.04913331 -0.53198276]]
mat2:
[[-0.34721774  0.33856995]
 [-1.33711593  0.76365454]
 [-0.51927188 -0.88550591]
 [ 0.18005875 -0.13655076]]
mat1 times mat2:
[[-2.28817208  0.29178687]
 [ 0.62638084 -2.47799506]
 [ 0.76190267  0.85059793]]


Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [47]:
# Run this cell
a = np.random.random((2,3))
print(a)

[[0.42652299 0.20597149 0.18409952]
 [0.62509513 0.13592701 0.02245816]]


In [48]:
# Calculating sum of all the elements of the array. 
# This method considers all the elements of array as a long list of numbers regardless of the shape.
add = a.sum()
print(add)

1.6000742942198987


In [52]:
# Find minimum and maximum from all the elements using a.min() and a.max() command.
minimum = a.min()
maximum = a.max()
print("minimum = %9.8f"%(minimum))
print("maximum = %9.8f"%(maximum))

minimum = 0.02245816
maximum = 0.62509513


In [53]:
# Create a random array a of dimension (4,6) and find sum , min, max as shown above.
a = np.random.randn(4,6)
add = a.sum()
minimum= a.min()
maximum= a.max()
print("The array a:")
print(a)
print("The sum of all elements of array a: %9.8f"%(add))
print("minimum = %9.8f"%(minimum))
print("maximum = %9.8f"%(maximum))

The array a:
[[-1.65734557  0.35466815  0.60250346  1.6426048  -0.73218414 -0.60611833]
 [ 0.90536347 -1.89824786  1.31135831 -0.07421862  0.14128955  0.71459356]
 [-0.58007013  0.88100272 -1.89408219 -0.97888006 -0.85302909  0.49739558]
 [-0.48367148 -0.93547756 -0.30858114 -0.65749796  1.93050006 -1.52502162]]
The sum of all elements of array a: -4.20314607
minimum = -1.89824786
maximum = 1.93050006


# Operations on rows or columns

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [94]:
# Run this cell
B = np.arange(12).reshape(3,4)
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [95]:
# sum along a column
column_sum = B.sum(axis=0)  
print(column_sum)

[12 15 18 21]


In [98]:
# sum along a row. In sum function above, in place of axis=0, pass axis=1
row_sum = B.sum(axis=1)
print("The row sums:")
print(row_sum)
# Minimum along row
min_row= B.min(axis=1)
print("The minimum item in every row:")
print(min_row)
# Minimum along column
min_column= B.min(axis=0)
print("The minimum item in every column:")
print(min_column)

The row sums:
[ 6 22 38]
The minimum item in every row:
[0 4 8]
The minimum item in every column:
[0 1 2 3]


In [99]:
# To apply universal mathematical functions on all the elements of a matrix, we do so as shown below:
B = np.arange(3)
print("The array B:")
print(B)
# Compute exponent of every element of B
C = np.exp(B) 
print("The array C:")
print(C)
# Compute sqrt of every element in B.  (You may get an error if an element in B is negative.)
D = np.sqrt(B)
print("The array D:")
print(D)

The array B:
[0 1 2]
The array C:
[1.         2.71828183 7.3890561 ]
The array D:
[0.         1.         1.41421356]


In [58]:
# Create a random matrix of dimensions (2,4) and apply the above three operations.
A = None
print("The array A:")
print(A)
# Apply operations on matrix A
B = None
print(B)
C = None
print(C)
# Perform np.log( ).  (Note: you will get error if you try to take the log of a negative number.)
D = None
print(D)

The array A:
None
None
None
None


# Transpose of a Matrix
There are 2 ways to get transpose of a numpy array. Either using .T attribute or using np.transpose(matrix) method.
Note: If you have a rank 1 matrix and you take it's transpose, it will be same as the original matrix.

In [59]:
# Using .T attribute
A = np.arange(4).reshape((2,2))
B = A.T
print("The original A:")
print(A)
print("The transpose of A:")
print(B)

The original A:
[[0 1]
 [2 3]]
The transpose of A:
[[0 2]
 [1 3]]


In [60]:
# Using transpose method
C = np.transpose(A)
print(C)

[[0 2]
 [1 3]]


In [61]:
# Create a random matrix X of dimension (4,3) and take it's transpose.
X = None
# Find transpose of X using any of the above method
Y = None
print("X: ")
print(X)
print("X Transpose: ")
print(Y)

X: 
None
X Transpose: 
None


# Indexing, slicing and iterating

Indexing, slicing and iterating on 1-dimensional arrays. 

Indexing, slicing and iterating is almost same as simple python lists for 1-dimensional arrays. 

Note: Index starts from 0.

In [62]:
# Run this cell
a = np.arange(15)**3
print(a)

[   0    1    8   27   64  125  216  343  512  729 1000 1331 1728 2197
 2744]


In [63]:
# Indexing. Getting third element of a
b = a[2]
print(b)
# Find fifth element of a
c = None
print(c)

8
None


In [64]:
# Slicing. Getting elements from index 2 to 5.  (Note we do not get the item at index 6.)
b = a[2:6]
print(b)
# Find elements from index 4 to 7.
c = None
print(c)

[  8  27  64 125]
None


In [65]:
# Reversing 1-D array
rev = a[::-1]
print(rev)

[2744 2197 1728 1331 1000  729  512  343  216  125   64   27    8    1
    0]


In [66]:
# Looping over some indices.
# Start from index 2, stop before index 12 and jump or increment by 3.
x = a[2:12:3]
print(x)
# Start from index 3, stop before index 12 and jump by 4.
y = None
print(y)

[   8  125  512 1331]
None


In [67]:
# Using a for loop to iterate:
for i in a:
    print(i)

0
1
8
27
64
125
216
343
512
729
1000
1331
1728
2197
2744


# Multidimensional arrays 
They can have one index per axis. These indices are given in a tuple separated by commas:

In [68]:
# Run this code
a = np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [69]:
# Element in third row and second column of the matrix.  
# Note due to indexing starting from 0, we use index 2 for the third row and we use index 1 for the second column
print(a[2,1])

7


In [70]:
# Find element in second row and third column. 
b = None
print(b)

None


In [71]:
# Getting each row in the second column of array a
c = a[: , 1]
print(c)

[ 1  4  7 10]


In [72]:
# Get each column in the second row of a.
d = None
print(d)

None


In [73]:
# a[i:j, : ] returns rows i+1 through j of the matrix.  (Yeah this is confusing due to indexing starting at 0!)
# In the code below we get rows 2 through 3 of the matrix.  (We index from 1 to (3-1).) 
e = a[1:3, : ]
print(e)

[[3 4 5]
 [6 7 8]]


In [74]:
# Get the last row
b = a[-1,:]
print(b)

[ 9 10 11]


In [75]:
# Find last column
c = None
print(c)

None


You can use a for loop to traverse through an array!!

In [76]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        print(a[i][j])

0
1
2
3
4
5
6
7
8
9
10
11


# Stacking together different arrays.

Several arrays can be stacked together along different axes:

In [77]:
# Run this cell
a = np.arange(4).reshape((2,2))
print(a)

[[0 1]
 [2 3]]


In [78]:
# Run this cell
b = np.arange(4,8).reshape((2,2))
print(b)

[[4 5]
 [6 7]]


To stack array b at the bottom of array a, we use vstack command. Note, for vstack, number of columns in both arrays should be same i.e. a.shape[1] == b.shape[1].

In [79]:
# Stacking b at the bottom of a.
c = np.vstack((a,b))
print(c)
print(c.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)


In [80]:
# Horizontal stack. Stack a to the left of b. 
# Note, for hstack, number of rows in both arrays should be same i.e. a.shape[0] == b.shape[0].
d = np.hstack((a,b))
print(d)

[[0 1 4 5]
 [2 3 6 7]]


In [81]:
# Create an array a of dimension (3,2) and another array b of dimension (3,5). 
# Append one of them to the left of another i.e. hstack.
a=None
b=None 
c=None
print("The array a:")
print(a)
print("The array b:")
print(b)
print("The array c:")
print(c)

The array a:
None
The array b:
None
The array c:
None


# Broadingcasting.

This is an important feature of numpy arrays. Suppose we have an array a of dimension (4,5) and another array b of dimension (4,1). If we want to add both the arrays, is it possible according to linear algebra? The answer is NO because in Linear Algebra, to perform element-wise arithmetic operations, dimensions should be same. 

However, using broadcasting it is possible to add the arrays. Broadcasting copies the first column of b to other columns of b to make it of same size as of a i.e. make it of dimension (4,5) from (4,1). 

In [82]:
a = np.arange(20).reshape((4,5))
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [83]:
b = np.arange(4).reshape((4,1))
print(b)

[[0]
 [1]
 [2]
 [3]]


In [84]:
c = a + b
print(c)

[[ 0  1  2  3  4]
 [ 6  7  8  9 10]
 [12 13 14 15 16]
 [18 19 20 21 22]]


For broadcasting to work, all the dimensions must be compatible. A dimension is compatible for both arrays either if  they are equal, or either of them is 1.  

For example: array b has dimensions (2,3,4) and array c has dimensions (1,3,2).  The first dimension is compatible because c.shape[0]=1.  The second dimension is compatible because b.shape[1]==c.shape[1].  But the third dimension is not compatible becaue b.shape[2] $\not =$ c.shape[2] and neither of them is 1.

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. 

When either of the dimensions compared is one, the other is used. In other words, dimensions with size 1 are stretched or “copied” to match the other.
In the following example, both the A and B arrays have axes with length one that are expanded to a larger size during the broadcast operation:

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

Another example:

A      (3d array):  15 x 3 x 5
B      (3d array):  15 x 1 x 5
Result (3d array):  15 x 3 x 5

Broadcasting rules can be confusing. But for now, you only need to know very basic broadcasting which is shown in the code cell above.

# Basic Linear Algebra Operations.

In [85]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [86]:
# To find Inverse of matrix a:
b = np.linalg.inv(a)
print(b)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [87]:
# Creating Identity matrix: Identity matrix is always a square matrix.
u = np.eye(3)
print(u)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [88]:
# Finding Trace of a matrix
c = np.trace(u)
print(c)

3.0


In [89]:
# Find eigen values of a matrix
d = np.linalg.eig(a)
print(d)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))


# Automatic Reshaping

In [90]:
# Run this cell
a = np.arange(30)
a.shape = 2,-1,3  # -1 means "whatever is needed"
print(a.shape)
print(a)

(2, 5, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


This assignment ends here. We hope this assignment gives you basic knowledge of using numpy and it's arrays and perform basic operations. We highly encourage you to use official numpy documentation if you need more help while solving your machine learning assignments. https://docs.scipy.org/doc/numpy-dev/user/quickstart.html . One of the topic not covered in this assignment is indexing with arrays of indices and indexing with  boolean arrays. Though not used much in the programming assignments, but can be helpful in some scenarios. You can find them in the given link above.